### ISSUE TITLE
Adaptive Mappings should detect conflicts with existing mappings

### ISSUE THREAD

**Issue by hjdivad** [dsawardekar/portkey#2]
Adaptive mappings result in quite a lot of mappings being created.  Unfortunately they can easily conflict with existing user mappings.  When this happens the failure mode is quite bad: vim waits a certain time after a substring mapping before deciding to use it.

For example if the user has a mapping for `<localleader>t` `ember.vim` will add mappings like `<localleader>ts` which results in `<localleader>t` taking a very long time to finish.

It would be great if portkey could detect this and alert the user rather than create the mapping.  The message could easily tell the user how to resolve the problem (ie specify a custom mapping in `portkey.json`).

**Comment by dsawardekar** [comment]
Good idea. I'll report back when I have it working.

**Comment by dsawardekar** [comment]
I've added this in `0.1.8`.

By defaults conflict messages will be shown. I've chosen to still add the portkey mappings even when conflicts are found. Partially because a warning should be sufficient to inform users of the conflict. And also since it's only an extra pause not an error. 

Thanks for reporting. I probably wouldn't have noticed this because my `ttimeout` is much shorter.

**Comment by hjdivad** [comment]
@dsawardekar awesome, thanks.  Although it doesn't matter for me any longer since I already dug through `ember.vim` and `portkeys` enough to figure out how to work around the issue, I expect this will make life much easier for other users.
