### ISSUE TITLE
What version of vim is required?

### ISSUE THREAD

**Issue by hjdivad** [dsawardekar/portkey#3]
I can't seem to find it in the docs.  I'm getting pretty brutal errors trying to use portkey via `ember.vim` on 7.3 but it seems to work fine on 7.4

**Comment by hjdivad** [comment]
I should clarify that I get these errors when I open a project using the recommended `portkey.json` in vim 7.3 but not when I open the same project in vim 7.4

``` js
// portkey.json
{
  "portkeys": ["ember"]
}

```

**Comment by dsawardekar** [comment]
To be honest I haven't tested on 7.3. I am running 7.4 and master. This is largely because of the segfaults in 7.3 when using with CtrlP.

About Vim's red screen of death, yeah it's pretty scary. But it isn't as terrible as it looks. What's happening is Vim finds one error say on line 1 of a function and throws an exception. But where it differs from saner languages is that it merrily continues to execute the rest of the function as if nothing happened. In reality all that is important is the first exception raised.

Can you post the error messages? To get at the errors easily, Run vim using `verbosefile` like below.

```
$ vim --cmd 'let &verbosefile="foo.log"'
```

Then do the operations that are causing errors, and close vim. You'll get a nice log file with the errors.

**Comment by hjdivad** [comment]
@dsawardekar as it happens I almost exclusively use vim7.4 via MacVim's `mvim -v`.  I run into this problem only when editing git commit messages, which will use `core.editor`, in my case `/usr/bin/vim`.  I could easily fix this problem locally by switching to `mvim` but I want something that will work on my (remote) pairing machine.

Plenty of debug output for you at https://gist.github.com/hjdivad/7236948

You will probably want to only look at the `standardverbosity` files.  I have included debug output for 7.3 and 7.4 as a comparison, and tried a minimal config that you should be able to replicate locally (`/usr/bin/vim -Vvim7.3.out.standardverbosity -u NONE --cmd "set rtp+=$HOME/.vim/bundle/ctrlp,$HOME/.vim/bundle/portkey,$HOME/.vim/bundle/ember.vim | set nocp|runtime! plugin/**/*.vim"` )

I have also included output for `-V20` although interestingly this causes errors in both 7.3 and 7.4: `E724: variable nested too deep for displaying`.  My guess is you have objects with circular refs that vim has trouble displaying in debug output or something similar.

**Comment by dsawardekar** [comment]
> as it happens I almost exclusively use vim7.4 via MacVim's mvim -v. I run into this problem only when editing git commit messages, which will use core.editor

That sounds like a legit reason. The segfault tends to happen on `<LocalLeader>foo` then `<Enter>`. Something to do with CtrlP closing out the buffer, that confuses Vim 7.3. You have been warned!

> Plenty of debug output for you at https://gist.github.com/hjdivad/7236948

Hmm looks like something simple. I'll take a look.

``` log
<SNR>15_s:ProjectionCollection_add:
line   16:
E488: Trailing characters
```

> My guess is you have objects with circular refs that vim has trouble displaying in debug output or something similar.

Yup, quite a few circular refs. Vim can't print circular references. That's unrelated to this issue though, I'm not printing anything in the release build.

**Comment by dsawardekar** [comment]
Ok I've isolated the issue. It's to do with [patch 97](https://code.google.com/p/vim/source/detail?r=faf4b09c396e#). 

The gist of it is that Vim without patch 97 has problems evaluating `if` statements that are false. Something like,

``` viml
if will_be_false
endif
```

makes Vim ignore the returns for Funcrefs. I ran the portkey test suite under Vim with and without patch 97. Without it there are about 35 errors with the same `Trailing characters` message. I found that `vim-rails` with `vim-bundler` had the [same issue](https://github.com/tpope/vim-bundler/issues/21#ref-pullrequest-14517824) that they fixed by refactoring such conditionals. 

Doing this in portkey would be quite tedious. I'm reluctant to do this at the moment. If possible update to at least patch 97.

I'll update the system requirements in the docs to reflect this.

**Comment by hjdivad** [comment]
@dsawardekar that's unfortunate.  I use a nitrious.io box for pairing.  I can't easily build a local vim there due to lack of storage.  Can you think of a workaround I could do on my end?

**Comment by dsawardekar** [comment]
@hjdivad I did a test on nitrous.io. It appears to use Vim 7.3 with patches 1-429. Portkey needs only upto 7.3 patch 97. So you should be fine. 

Note: I fixed an unrelated issue regarding adaptive mappings for 7.3. You'll need 0.1.10.

The test suite runs fine on 7.3 p429. I don't see any other problems running on nitrous.io. Let me know if you find any other issues.

**Comment by hjdivad** [comment]
@dsawardekar awesome.  Everything seems to be working now; thanks.
