### ISSUE TITLE
Portkey raises error when booting Vim for git commit

### ISSUE THREAD

**Issue by nelstrom** [dsawardekar/portkey#6]
I have no problems with portkey when I launch Vim in the usual fashion, but something goes wrong when I run `git commit`, which launches Vim. I see an error message (see screenshot) for a second before I can operate Vim.

![portkey-error-on-vim-boot](https://f.cloud.github.com/assets/7069/1922724/80ca52b8-7e0a-11e3-9c58-a8036fb72560.png)

The error message reads: `Error detected while processing function <SNR>44_s:Plugin_on_buffer_open`. Any idea what could be causing this?

**Comment by nelstrom** [comment]
I've been digging a little deeper and realized that my `.gitconfig` file was referencing Vim 7.3. I've updated it to use Vim 7.4 and now the problem has gone away.

**Comment by dsawardekar** [comment]
@nelstrom Happy new year! 

This issue is similar to #3. I haven't gotten around to figuring out an alternate to upgrading. The issue relates to the use of `unless` blocks to return early in some places. Vim 7.3 without p97 ignores return statements within such blocks. 

For now the minimum requirement for portkey is 7.3 p97.

**Comment by lluchs** [comment]
Is it possible to check vim patch level when the plugin loads? A message advising to upgrade vim would be useful.

**Comment by nelstrom** [comment]
@lluchs the same thought occurred to me. Although perhaps it would be less intrusive if portkey simply didn't load if the minimum requirements weren't met. The [documentation on v:version](http://vimdoc.sourceforge.net/htmldoc/eval.html#version-variable) explains how to check version and patch levels.

**Comment by dsawardekar** [comment]
I've added an ifdef to prevent loading of the plugin if system requirements aren't met. Currently chosen to go without a warning because it would mean a `Press ENTER or type command to continue` prompt on startup, which I'd like to avoid.

I've updated the Readme to document the minimum system requirements. Here's hoping that people trying Portkey on older Vim don't end up thinking it does absolutely nothing!!! ;-)
